version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gestionfoyer
    ports:
      - "3307:3307"
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    build: ./myFirstProject
    restart: always
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3307/gestionfoyer?useSSL=false&createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  frontend:
    image: mondherar/angular:latest
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - app
    
volumes:
  db:
