apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: default

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # You can adjust the size as needed
  storageClassName: standard  # Make sure this matches your Kubernetes storage class
