---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8089        # Service port inside cluster
      targetPort: 8089  # Pod container port
      nodePort: 31089   # Fixed NodePort to expose externally
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: ClusterIP  # Exposed externally via Ingress (not NodePort!)
