apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default  # Ensure the namespace is correctly set
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: NodePort  # Change ClusterIP to NodePort
  nodePort: 30089  # Specify a port in the range 30000-32767

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default  # Ensure the namespace is correctly set
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: NodePort  # Change ClusterIP to NodePort
  nodePort: 30080  # Specify a port in the range 30000-32767
