apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default  # Namespace for backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 4200
      nodePort: 30080
